#ifndef EMBEDDED_FONT_HPP
#define EMBEDDED_FONT_HPP

#include <cstdint>

// These symbols are automatically generated by the linker
extern "C" {
    extern uint8_t _binary_font_ttf_start[];
    extern uint8_t _binary_font_ttf_end[];
}

// Helper to get size
inline size_t GetFontSize() {
    return _binary_font_ttf_end - _binary_font_ttf_start;
}

#endif